### ISSUE TITLE
Implementação do Jwt 

### ISSUE THREAD

**Issue by marcelomnzs** [alinevenceslau/livrariadagenteup#17]
Eu **como** desenvolvedor **quero** implementar o JWT (JSON Web Token) **para** que o usuário receba um token bearer ao se autenticar na página

- [x] Criar o controller Auth do JWT
- [x] Criar as rotas
- [x] Criar arquivos de configuração do JWT

**Comment by marcelomnzs** [comment]
**Tasks feitas** no commit: 948870c9822e7af06f964cfcc57b07e2cafb2ec3
